export const QueryKeys = {
  bounty: (bountyId: string) => ["bounty", bountyId],
  bountyComments: (bountyId: string) => ["bounty", bountyId, "comments"],
  proposal: (proposalId: string) => ["proposal", proposalId],
  proposalComments: (proposalId: string) => ["proposal", proposalId, "comments"],
  deliverable: (deliverableId: string) => ["deliverable", deliverableId],
  chains: () => ["supportedChains"],
  networksByChain: (chainId: string) => ["networks", chainId],
  networksByGovernor: (governorAddress: string, chainId: string) => ["network", governorAddress, chainId],
  networkDefault: () => ["network", "default"],
  tokensByChain: (chainId: string) => ["tokens", chainId],
  tokensOf: (wallet: string) => ["tokens", wallet],
  votingPowerOf: (wallet: string) => ["voting-power-multi", wallet],
  votingPowerMultiOf: (wallet: string) => ["voting-power-multi", wallet],
};