export enum ReduceActionName {
  MetaMaskWallet = "MetaMaskWallet",
  Loading = "Loading",
  BeproInit = "BeproInit",
  MyIssues = "MyIssues",
  Oracles = "Oracles",
  Staked = "Staked",
  ChangeAddress = "ChangeAddress",
  AddToast = "AddToast",
  RemoveToast = "RemoveToast",
  MyTransactions = "MyTransactions",
  AddTransactions = "AddTransactions",
  UpdateTransaction = "UpdateTransaction",
  ChangeMicroServiceReadyState = "ChangeMicroServiceReadyState",
  ChangeNetwork = "ChangeNetwork",
  ChangeNetworkId = "ChangeNetworkId",
  handle = "handle",
  ChangeTransactionalTokenApproval = "ChangeTransactionalTokenApproval",
  ChangeSettlerTokenApproval = "ChangeSettlerTokenApproval",
  ChangeNetworksSummary = "ChangeNetworksSummary",
  ClearTransactions = "ClearTransactions",
  ShowWeb3Dialog = "showWeb3Dialog",
  ChangeSettings = "ChangeSettings",
}
